---
services:
  queue:
    image: redis
    ports:
      - 6379:6379
  db:
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=Park123!
    volumes:
      - ./data:/tmp/data
  web:
    image: seait
    ports:
      - 5000:5000
    environment:
      - MONGODB_URL=mongodb://mongo:Park123!@db:27017/seait?authSource=admin
      - MONGODB_DB=seaitdb
      - REDIS_URL=redis://queue:6379
      - REDIS_QUEUE_NAME=seait_queue
      - PORT=5000
    depends_on:
      - queue
      - db
