$APP_NAME="seait"
#invoke-expression "heroku login"
invoke-expression "heroku container:login"
#invoke-expression "heroku create $APP_NAME"
invoke-expression "docker tag $APP_NAME registry.heroku.com/$APP_NAME/web"
invoke-expression "docker push registry.heroku.com/$APP_NAME/web"
invoke-expression "heroku container:release --app $APP_NAME web"
invoke-expression "heroku open --app $APP_NAME"
invoke-expression "heroku logs --app $APP_NAME --tail"